#Get all posts
GET http://localhost:3334/api/posts/?page=1&sortBy=creationDate HTTP/1.1

###

#Get post by Id
GET http://localhost:3334/api/posts/14 HTTP/1.1

###

#Create new post
POST http://localhost:3334/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MxYzZlOWI2ZDg3OTNlZTViY2E3MDkiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6IkpvaG4iLCJzdXJuYW1lIjoiRG9lIiwiaWF0IjoxNjczNjk3MjE4LCJleHAiOjE2NzM2OTgxMTh9.X0vxANVw-y_A09ej7LonKXj9qTrdcGLBgyFYTIv-JfQ

{
  "postType": "quote",
  "postState": "published",
  "isRepost": false,
  "text": "По большей части",
  "author": "Аристотель",
  "tags": []
}

###

#Update post
PATCH http://localhost:3334/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MxYzZlOWI2ZDg3OTNlZTViY2E3MDkiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6IkpvaG4iLCJzdXJuYW1lIjoiRG9lIiwiaWF0IjoxNjczNjk3MjE4LCJleHAiOjE2NzM2OTgxMTh9.X0vxANVw-y_A09ej7LonKXj9qTrdcGLBgyFYTIv-JfQ

{
  "id": 14,
  "text": "По большей части будущее подобно прошедшему"

}

###

#Delete post
DELETE http://localhost:3334/api/posts/14 HTTP/1.1

###
